parameters:
#    sbbs_front.example.class: Sbbs\FrontBundle\Example

services:
#    sbbs_front.example:
#        class: %sbbs_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
