sbbs_api:
    resource: "@SbbsApiBundle/Resources/config/routing.yml"
    prefix:   /

sbbs_front:
    resource: "@SbbsFrontBundle/Controller"
    type: annotation
    prefix:   /

sbbs_main:
    resource: "@SbbsMainBundle/Resources/config/routing.yml"
    prefix:   /

